// GENERATED by gen_family_table.py from X-Plane's shipped SPIR-V pack
// (Resources/shaders/bin/spv.zip, hashed with the injection's FNV-1a-64).
// Regenerate after an X-Plane update changes the shader pack.
// Policy and reasoning live in the generator's header comment.
#pragma once
#include <cstdint>
#include <cstddef>

static const uint64_t kMvZeroVert[] = {
    0x04ce2312cc9f2ddfull, // legacy_flat_0.spv
    0x0bd2996cbdf4e8a1ull, // legacy_flat_14.spv
    0x0d39bae6a987c27full, // legacy_depth_5.spv
    0x10884d72601b0c97ull, // legacy_depth_0.spv
    0x1fc91a030274fd89ull, // legacy_depth_7.spv
    0x218991c0d550cd0eull, // rain_draw_0.spv
    0x25a337426e788cb4ull, // font_0.spv
    0x2b6d0ff8119e6327ull, // legacy_flat_2.spv
    0x2ba023b8b9adad1aull, // font_2.spv
    0x2e4a3f7e53261484ull, // legacy_depth_3.spv
    0x47bf557606b9c338ull, // legacy_flat_13.spv
    0x49ab4cd57e4ec930ull, // font_5.spv
    0x4f94900068adf5cdull, // legacy_depth_2.spv
    0x54d8f651063a9bd5ull, // legacy_flat_12.spv
    0x5cd6db920c9883bcull, // legacy_depth_4.spv
    0x5ed4dbab8f73aa36ull, // legacy_flat_7.spv
    0x616e5e5200724864ull, // legacy_flat_3.spv
    0x69616891c5966bcfull, // font_4.spv
    0x715b745719db553dull, // legacy_flat_10.spv
    0x73927eca54e181d0ull, // rain_surface_0.spv
    0x898cc9d03b362e7cull, // legacy_flat_9.spv
    0xac2254b4079bce56ull, // manip3d_0.spv
    0xad15482df53363c4ull, // legacy_depth_8.spv
    0xaf0dbbc03cd4dae1ull, // rain_0.spv
    0xb1e87ffccc4fbcc6ull, // legacy_depth_9.spv
    0xb30e80afd8273157ull, // legacy_flat_4.spv
    0xc9aa50c5841944eeull, // rain_draw_2.spv
    0xd29e09f63fd88f35ull, // legacy_flat_8.spv
    0xf4f9e0890d431112ull, // legacy_flat_5.spv
};
static const size_t kMvZeroVertCount = sizeof(kMvZeroVert) / sizeof(kMvZeroVert[0]);

static const uint64_t kMvGroundVert[] = {
    0x00914aa2a6deb744ull, // terrain_1578.spv
    0x022e840923e3c445ull, // terrain_2516.spv
    0x02dfbd1c6f27dda9ull, // fake_terrain_8.spv
    0x02fb280e646ef328ull, // terrain_2218.spv
    0x036957fe0d77bcf7ull, // terrain_66.spv
    0x0605e317fa02bd70ull, // astronomical_6.spv
    0x063a8d3c75fe7d38ull, // terrain_2518.spv
    0x06644c9d4b1f4b51ull, // terrain_892.spv
    0x07ce74bc6f05014eull, // terrain_17.spv
    0x0860ba37ed8fc396ull, // terrain_1920.spv
    0x08e32b7223d2debcull, // terrain_1710.spv
    0x09028314a561dcbaull, // terrain_960.spv
    0x0948e51230a564ebull, // terrain_2224.spv
    0x09e893c8b68bceb1ull, // terrain_2227.spv
    0x09fddb8085945b35ull, // terrain_1930.spv
    0x0b825406deb95385ull, // terrain_841.spv
    0x0bb3ea4e19567be9ull, // terrain_1594.spv
    0x0bbac1f7c60e9e00ull, // terrain_887.spv
    0x0bca563b2cef054aull, // terrain_1242.spv
    0x0c563b2ca2d8b288ull, // terrain_38.spv
    0x0caec7601769093eull, // terrain_1900.spv
    0x0da62c91713f509cull, // terrain_2682.spv
    0x0da89ee1397fa070ull, // terrain_2247.spv
    0x0daa80097e53f008ull, // terrain_1613.spv
    0x0ec586fe5028972dull, // ground_lights_0.spv
    0x103226286bf9af5dull, // terrain_32.spv
    0x10c6292111bf8aadull, // terrain_35.spv
    0x10d9cc57bc0529a2ull, // terrain_3164.spv
    0x111ddcfed3c3df31ull, // terrain_2684.spv
    0x12a55920e69211f6ull, // terrain_101.spv
    0x139d349a33e3fff5ull, // terrain_31.spv
    0x13b128040a69bbf4ull, // terrain_742.spv
    0x13bfd9a51199661eull, // terrain_977.spv
    0x140165a1ce674d4eull, // terrain_302.spv
    0x143f7b16d8c842dfull, // terrain_1588.spv
    0x147b7c3fb55a14d9ull, // terrain_894.spv
    0x156198d4d32f3cf6ull, // terrain_3036.spv
    0x15877eaac961f3eeull, // terrain_2352.spv
    0x15b58aeaf0771010ull, // terrain_3030.spv
    0x15b896837a806c59ull, // terrain_774.spv
    0x161a661ccddb5beaull, // terrain_834.spv
    0x170d95df7f6d285dull, // terrain_782.spv
    0x17350887229623cbull, // terrain_132.spv
    0x188c163cb0e2185full, // terrain_970.spv
    0x194e0d5f25625907ull, // terrain_2858.spv
    0x19adc7b71a737084ull, // terrain_3076.spv
    0x1a56cd776f3202d3ull, // terrain_2521.spv
    0x1b1e634b53349595ull, // terrain_786.spv
    0x1c78fcef28d99be9ull, // terrain_3028.spv
    0x1d256225c9643963ull, // terrain_839.spv
    0x1dc5bdff6c11bd33ull, // terrain_792.spv
    0x1de3c361fd3b32c6ull, // terrain_2866.spv
    0x1e48b0452214db86ull, // terrain_3066.spv
    0x1f56728d0d4d4b44ull, // terrain_1714.spv
    0x206f00d3ead577d3ull, // fake_terrain_3.spv
    0x20dea2eb5c564f60ull, // terrain_2262.spv
    0x2320f6d4a9a60ea7ull, // terrain_2036.spv
    0x2604df1525c4c34bull, // terrain_2575.spv
    0x26bea51db6245c62ull, // terrain_1620.spv
    0x275d53ad816f35fbull, // terrain_3048.spv
    0x27c3b62de74333cbull, // terrain_2678.spv
    0x29a3fc06436565f7ull, // terrain_2554.spv
    0x29a5273925ea135bull, // terrain_779.spv
    0x2a1ef2848a2461c8ull, // terrain_2960.spv
    0x2ad7e6dbce85f245ull, // terrain_2716.spv
    0x2ae255a7fb0322d1ull, // terrain_414.spv
    0x2b5769f8d23914d8ull, // terrain_872.spv
    0x2b8c2e52b9c0025bull, // terrain_1604.spv
    0x2c2319de719dda50ull, // terrain_901.spv
    0x2c250cbf2900022dull, // fake_terrain_0.spv
    0x2c6f6738e66c96b3ull, // terrain_2264.spv
    0x2cde88bb8074bd76ull, // terrain_3248.spv
    0x2d496be2e995dcdfull, // terrain_1932.spv
    0x2e26b2dc20feab5full, // terrain_844.spv
    0x2e32e2e2a0e4d227ull, // terrain_33.spv
    0x2ed836c3bdac8a0bull, // terrain_124.spv
    0x2ee0a5a687de6eddull, // terrain_748.spv
    0x2f794a06c0d6f13cull, // terrain_1163.spv
    0x2fd1f28e69367f72ull, // terrain_2572.spv
    0x30131a3e6d37c9e8ull, // terrain_2542.spv
    0x304477e08b1fd3ebull, // terrain_1870.spv
    0x3090afcca7acd5e4ull, // terrain_1892.spv
    0x30efc1a62f676685ull, // airport_raster_0.spv
    0x3139fc86c54b096full, // terrain_902.spv
    0x313d6df56ef2c62eull, // terrain_918.spv
    0x31d85616ce7a19cbull, // terrain_2222.spv
    0x31fdc90a99c6c790ull, // terrain_2502.spv
    0x320d2cb2031feb36ull, // terrain_771.spv
    0x3234e4e1bf569652ull, // terrain_410.spv
    0x339f1493b71fe984ull, // terrain_3128.spv
    0x34d943155d8f2737ull, // terrain_738.spv
    0x34ecbb392eda2eeaull, // terrain_744.spv
    0x35486d052fcc304cull, // terrain_2088.spv
    0x3602feca1d12d459ull, // terrain_70.spv
    0x375712800026b907ull, // terrain_922.spv
    0x375dacf29eefbff3ull, // terrain_1950.spv
    0x377e38f70c865a14ull, // ocean_shading_41.spv
    0x37f04748873ef50full, // terrain_119.spv
    0x37f442b226618889ull, // terrain_2594.spv
    0x3918fcb589d2b69aull, // terrain_2034.spv
    0x3964aa8ba4271ec8ull, // terrain_1760.spv
    0x3b32537e45edf4e6ull, // astronomical_8.spv
    0x3b349f434454a92full, // terrain_2510.spv
    0x3c0d0d54dc638800ull, // ocean_shading_38.spv
    0x3c2ec94d011f9248ull, // astronomical_5.spv
    0x3c64c9c564c5ea3cull, // terrain_2024.spv
    0x3cab0fd1ca9353d1ull, // terrain_3046.spv
    0x3e21ec4f86b28837ull, // terrain_3124.spv
    0x3ecf3eca49e01c5eull, // terrain_324.spv
    0x40e65dd291c32138ull, // terrain_1952.spv
    0x41a2e0ee841cc16dull, // terrain_1615.spv
    0x4263611a55f19166ull, // terrain_905.spv
    0x4357eb082c86af95ull, // line3d_2.spv
    0x44db4f76f5e0226cull, // terrain_2578.spv
    0x45ea254b9d542413ull, // terrain_2852.spv
    0x466be2c61bf526a7ull, // terrain_2032.spv
    0x48507ef0f61960c1ull, // terrain_1702.spv
    0x485fb95754765b80ull, // terrain_1144.spv
    0x4a0fabe5e41d4c5full, // terrain_1708.spv
    0x4c482968c6281459ull, // terrain_836.spv
    0x4c50141b8430ce0aull, // terrain_2230.spv
    0x4d079b07c4316b6cull, // terrain_925.spv
    0x4d5f2386124c5b61ull, // terrain_2267.spv
    0x4d747a0b81b3b52dull, // terrain_2246.spv
    0x4d877adef4db564dull, // terrain_2604.spv
    0x4ead50d4d027595bull, // terrain_966.spv
    0x4f50bfb090d090c8ull, // terrain_117.spv
    0x4f766a81d2148588ull, // terrain_754.spv
    0x5129e03517c16b5full, // terrain_1700.spv
    0x54c4c653fc93e41eull, // terrain_2599.spv
    0x54c699f2370b36adull, // terrain_899.spv
    0x55d93fa4c3818a5dull, // terrain_934.spv
    0x5659ef35c2bb9b1dull, // terrain_1936.spv
    0x566ca898df44c094ull, // terrain_2918.spv
    0x56d402dc5241fc83ull, // terrain_2350.spv
    0x594712645a228135ull, // terrain_794.spv
    0x59fa39b9d8d351c4ull, // terrain_2540.spv
    0x5b870b83db80e92aull, // terrain_2534.spv
    0x5bec153466fea433ull, // terrain_968.spv
    0x5c072c59fb037f29ull, // terrain_406.spv
    0x5c6e95d67bd224c0ull, // terrain_1244.spv
    0x5d1261496ce8bc66ull, // terrain_903.spv
    0x5d53c5096aaea9f7ull, // astronomical_2.spv
    0x5e8d4b8abc18839aull, // terrain_68.spv
    0x5f0246348a571be0ull, // terrain_412.spv
    0x5fe9c58b96b62630ull, // terrain_1866.spv
    0x60231ab5c1d88750ull, // terrain_1922.spv
    0x602fe4fb386875a5ull, // terrain_1762.spv
    0x6121b4cf171e96a8ull, // terrain_2344.spv
    0x61718251093aa931ull, // terrain_1147.spv
    0x617a9b95169c4cf5ull, // terrain_1161.spv
    0x61f51d014feca2f1ull, // terrain_828.spv
    0x647b22b6a52f98baull, // terrain_1939.spv
    0x65e608e839e6d4c1ull, // terrain_1632.spv
    0x665eef39073dab56ull, // terrain_933.spv
    0x6908b3bfc1204ebaull, // terrain_1628.spv
    0x6926ef8d3b19c38aull, // terrain_932.spv
    0x69c08081e2af6c2cull, // terrain_1943.spv
    0x6a29f0a1a078bbd0ull, // terrain_3071.spv
    0x6a90117a5b31a97dull, // terrain_1888.spv
    0x6b6d4efc928e9d2aull, // terrain_2579.spv
    0x6c2fa2256a2936bdull, // terrain_878.spv
    0x6cf19aea8466339dull, // terrain_2920.spv
    0x6ddc4dccb2a1bab1ull, // terrain_2.spv
    0x6e2266fc273cb1a0ull, // terrain_889.spv
    0x6e48aa1a5d61cae7ull, // terrain_2022.spv
    0x702980170035138eull, // terrain_2566.spv
    0x70396e5045878359ull, // terrain_1246.spv
    0x707cb15151de9040ull, // terrain_896.spv
    0x70840b4682274dd1ull, // terrain_935.spv
    0x70c65af39f202563ull, // terrain_316.spv
    0x713d9b7a8885468cull, // terrain_1882.spv
    0x72311dc1a640aebdull, // terrain_67.spv
    0x7239f7705e998765ull, // terrain_3130.spv
    0x72db953245cf7e45ull, // terrain_111.spv
    0x73415ffb266e5b47ull, // terrain_1166.spv
    0x736950643d2b336eull, // terrain_769.spv
    0x73ddd4b94fdbd4f2ull, // terrain_56.spv
    0x741314a8fdbbc184ull, // terrain_821.spv
    0x749c6d35c1b7b733ull, // terrain_2562.spv
    0x74a11214dcfa73fdull, // terrain_2567.spv
    0x74f231330e75c5caull, // terrain_2508.spv
    0x755b1e8e4884321cull, // terrain_2235.spv
    0x7597beb4c35fd1f8ull, // terrain_2926.spv
    0x75f7c99e3198d03eull, // terrain_818.spv
    0x7623ca6d4f2f489bull, // terrain_1954.spv
    0x76a8ddd2c099d9deull, // terrain_3042.spv
    0x7778722072f12c60ull, // terrain_2214.spv
    0x77a6b5d20e1730f1ull, // terrain_2270.spv
    0x7806d8c0ff1498b7ull, // terrain_990.spv
    0x789d718c433f7b7full, // terrain_2569.spv
    0x7a72b8f578ecfac8ull, // tchotchke_0.spv
    0x7b059652ba2cf2e4ull, // terrain_740.spv
    0x7b5114205152ac12ull, // terrain_3068.spv
    0x7c33132dfcf87a66ull, // terrain_1602.spv
    0x7c727aae3914bd98ull, // terrain_114.spv
    0x7cf10945c3502bf6ull, // terrain_2861.spv
    0x7cfd9b2511228f87ull, // terrain_746.spv
    0x7e55c7a5e937bad4ull, // terrain_1606.spv
    0x7e5f73f2530db9cfull, // terrain_1896.spv
    0x7e71657d64edd75cull, // terrain_321.spv
    0x7e83d80461101a1cull, // terrain_48.spv
    0x7efe3b107b98d799ull, // terrain_2862.spv
    0x7f08c6a943f1bd56ull, // terrain_1619.spv
    0x7f0ee6a2287310a4ull, // terrain_1584.spv
    0x7f416968370ed263ull, // terrain_2212.spv
    0x7f4e219a54d52d1aull, // terrain_995.spv
    0x7f783987c8a5bb5dull, // terrain_2850.spv
    0x7fe8cb55a93b00f6ull, // terrain_1878.spv
    0x80ff1e4b9e2d2ba0ull, // terrain_137.spv
    0x81927b8b5ab21f91ull, // terrain_5.spv
    0x8389952d205b0382ull, // ocean_shading_0.spv
    0x84047d3e629820d5ull, // terrain_880.spv
    0x8438ecaf1610e932ull, // terrain_7.spv
    0x859bcbc125935e67ull, // terrain_1764.spv
    0x85b4dda4cbc5cb28ull, // terrain_980.spv
    0x85cc48f139078425ull, // terrain_1941.spv
    0x86ce27f37d624fcdull, // terrain_1623.spv
    0x8704e8ee2618b295ull, // terrain_784.spv
    0x87530f4f7e85bcb7ull, // terrain_1925.spv
    0x8773b1db3c2da7d0ull, // terrain_408.spv
    0x881c87e45a7c6e5cull, // terrain_2240.spv
    0x888520385157d281ull, // terrain_915.spv
    0x89028697fb11861bull, // terrain_973.spv
    0x891b7371154c7386ull, // terrain_134.spv
    0x8a11261788042a67ull, // terrain_12.spv
    0x8aa31636e1cb830dull, // terrain_929.spv
    0x8b2c4685864f1b94ull, // terrain_1898.spv
    0x8c256df8b326449dull, // terrain_106.spv
    0x8fa238d858cb528eull, // dome_0.spv
    0x90900231dc825dd1ull, // terrain_2346.spv
    0x919a421e11a56082ull, // terrain_1248.spv
    0x9290101d76343615ull, // terrain_122.spv
    0x93628dc73a9c4025ull, // terrain_843.spv
    0x938df687c0c22195ull, // terrain_27.spv
    0x93962b5cac570820ull, // terrain_2676.spv
    0x95390442bc82a233ull, // terrain_1622.spv
    0x957c10a885374c32ull, // terrain_1938.spv
    0x96139c2979c2378dull, // terrain_1868.spv
    0x974ec3d43e4e27b9ull, // terrain_1621.spv
    0x98356bb9284f1a7cull, // terrain_2084.spv
    0x984a96bd53f771aaull, // terrain_1149.spv
    0x99975446205df0a4ull, // terrain_129.spv
    0x999da358ccb2ca0bull, // terrain_1902.spv
    0x999e8f0473e840f1ull, // terrain_103.spv
    0x99d3b6134f6101f3ull, // terrain_876.spv
    0x9a80449e75c7f198ull, // terrain_993.spv
    0x9b851d1890b29007ull, // terrain_2086.spv
    0x9c337bc7e9b61373ull, // terrain_1617.spv
    0x9db647d54a7fb123ull, // terrain_1944.spv
    0x9ecd92436d91bd51ull, // terrain_3034.spv
    0x9f9cc80bea201f86ull, // terrain_20.spv
    0x9fc9385c76a068b4ull, // terrain_1934.spv
    0x9fe7cd6794811635ull, // terrain_1928.spv
    0xa0efb6d0bd7211edull, // terrain_2958.spv
    0xa0f5a41fae1bb89eull, // terrain_826.spv
    0xa1f99e1612565fcaull, // terrain_1596.spv
    0xa393ebb12428ba48ull, // terrain_3065.spv
    0xa4745bb277532db7ull, // terrain_2026.spv
    0xa594d3656b1bfe37ull, // terrain_1608.spv
    0xa6ca2e79908bd07bull, // terrain_1252.spv
    0xa76fe1cd16b18c8eull, // terrain_3060.spv
    0xa7d39ea1b3a0f451ull, // terrain_1630.spv
    0xa7e13a1d2e197cf8ull, // terrain_1886.spv
    0xa9ba093917f6403aull, // terrain_1872.spv
    0xa9cd300a4188f545ull, // terrain_15.spv
    0xaa865bbdad8f7786ull, // terrain_1956.spv
    0xabc159126368d17cull, // terrain_1605.spv
    0xabf226336eaa7382ull, // terrain_2234.spv
    0xabf6321c18db02bfull, // terrain_2872.spv
    0xac47dab45a52dc9dull, // terrain_1876.spv
    0xad29fff0cf535dd5ull, // terrain_1924.spv
    0xad3be64e4a982577ull, // terrain_1918.spv
    0xad54a08c1b0b29d4ull, // terrain_2384.spv
    0xad5fc4f0e500d7ccull, // terrain_126.spv
    0xad7e2e42a79edbb1ull, // terrain_882.spv
    0xae13336fa9740461ull, // terrain_59.spv
    0xae4a51bba1e1c4c8ull, // terrain_23.spv
    0xaeafaaed550ba5d4ull, // terrain_34.spv
    0xaf3909f424a1a16bull, // terrain_69.spv
    0xb02183467ce71200ull, // terrain_25.spv
    0xb067232ea344dd79ull, // terrain_904.spv
    0xb0cb066ddcf4d89cull, // terrain_846.spv
    0xb103297643db39dfull, // terrain_997.spv
    0xb195da6285d76b8full, // terrain_53.spv
    0xb1972a174a3b419cull, // terrain_3122.spv
    0xb197cd27b243f968ull, // terrain_766.spv
    0xb1aa6a9334bf073cull, // terrain_2233.spv
    0xb239f623cd9ea427ull, // terrain_1152.spv
    0xb29c1503b8e709c9ull, // terrain_2386.spv
    0xb5026c3cbb3bfc1dull, // terrain_1582.spv
    0xb563fdbd89f70f72ull, // terrain_920.spv
    0xb5c262f5fa0574f6ull, // terrain_3064.spv
    0xb5d5da9a662879deull, // terrain_1766.spv
    0xb6fe70cbd6cbe679ull, // terrain_43.spv
    0xb77597a4bd16f307ull, // terrain_61.spv
    0xb8efcf28b0eb095full, // terrain_936.spv
    0xbbf409ae6f52fe79ull, // terrain_2860.spv
    0xbcde2716ee37f5f4ull, // terrain_319.spv
    0xbd9ab40167722dc7ull, // terrain_964.spv
    0xbeb1489777ffc906ull, // terrain_823.spv
    0xbeb3411a68ea2e74ull, // terrain_756.spv
    0xc0fce936cfe97e11ull, // terrain_94.spv
    0xc1f72bef90f9731dull, // terrain_2565.spv
    0xc2172200c0f209a5ull, // terrain_1931.spv
    0xc2fe17957a457456ull, // terrain_913.spv
    0xc31495f1061c98f1ull, // terrain_2864.spv
    0xc44a033a62b0a73cull, // terrain_789.spv
    0xc511444c78ec6500ull, // terrain_2030.spv
    0xc5d3598c921a33c8ull, // terrain_1600.spv
    0xc67da27315710c84ull, // terrain_0.spv
    0xc72c2d96970063c4ull, // terrain_1712.spv
    0xc8250ab426fc2cecull, // terrain_986.spv
    0xc87edf700f272b15ull, // terrain_759.spv
    0xc88371d23c97406cull, // terrain_777.spv
    0xc9a2779d2c75faaeull, // terrain_3062.spv
    0xca72fd0e5d2eebb3ull, // terrain_1945.spv
    0xcad117a0a41d12eeull, // terrain_1927.spv
    0xcb5f2675c7f889c3ull, // terrain_816.spv
    0xcc768bf04c96cce6ull, // astronomical_0.spv
    0xcd38ee1534c4f4edull, // terrain_45.spv
    0xcd7f701428765187ull, // terrain_1704.spv
    0xcdad1a08a48d253aull, // terrain_962.spv
    0xcdcab7fa2b6d3451ull, // astronomical_3.spv
    0xcfee7503490a1667ull, // terrain_1586.spv
    0xd02ca0b701fa2744ull, // terrain_1609.spv
    0xd0dda1bd88f06867ull, // terrain_909.spv
    0xd1006f9e06fb9d00ull, // terrain_975.spv
    0xd1597207eaaee55bull, // ocean_shading_3.spv
    0xd23e3ef471e845ceull, // terrain_874.spv
    0xd28a1872a4be5940ull, // terrain_900.spv
    0xd3d416d559c569b1ull, // terrain_3040.spv
    0xd3e94cdf37cbec23ull, // terrain_837.spv
    0xd41b2fba03743a5dull, // terrain_305.spv
    0xd4327cfbbb1d7b56ull, // terrain_9.spv
    0xd494cc698e7b3a35ull, // terrain_3070.spv
    0xd5096b2374124327ull, // terrain_51.spv
    0xd56582dafbce0f9aull, // terrain_2874.spv
    0xd869f27169bb32a3ull, // terrain_1880.spv
    0xda907327757a125cull, // terrain_2237.spv
    0xdad0366175ae4af1ull, // terrain_1929.spv
    0xdb00c3534201c167ull, // terrain_1942.spv
    0xdc023a8bfe069029ull, // terrain_2556.spv
    0xdd388cec29f7c5afull, // terrain_36.spv
    0xdd80ea5d2c20b593ull, // terrain_1607.spv
    0xdd8d78b895bfa09bull, // terrain_2536.spv
    0xde17327e2b8da160ull, // terrain_2867.spv
    0xde73dcd64f059ae3ull, // terrain_307.spv
    0xdf30f62202d0fadaull, // terrain_2020.spv
    0xdf66ac151e399196ull, // terrain_988.spv
    0xdf99636a3c9e0114ull, // terrain_797.spv
    0xdfb37545ceb472d3ull, // line3d_0.spv
    0xe06369fb1bd2aff5ull, // terrain_109.spv
    0xe1f951bedadf62e3ull, // terrain_310.spv
    0xe24081c34f410295ull, // fake_terrain_7.spv
    0xe28607649eb9f29bull, // terrain_984.spv
    0xe2d9f71f51f19636ull, // terrain_3162.spv
    0xe3e14a157a076638ull, // terrain_911.spv
    0xe54dbcc460c3618full, // terrain_1611.spv
    0xe5b347baadbc17d5ull, // terrain_2718.spv
    0xe5fe6fc057f9d3efull, // terrain_885.spv
    0xe61f7a2e008b2763ull, // terrain_907.spv
    0xe66ffdec6449ca3full, // terrain_71.spv
    0xe7f7be8cb5c5bac5ull, // terrain_1598.spv
    0xebec4f0896ab5b01ull, // terrain_1250.spv
    0xec661c38b03fc417ull, // terrain_2602.spv
    0xec768feae2d15f79ull, // terrain_2216.spv
    0xecf06bb5b9084078ull, // terrain_2243.spv
    0xed616c4ef4563cacull, // terrain_927.spv
    0xedc672c46b6e782cull, // terrain_2272.spv
    0xee06a7bf6eac0539ull, // terrain_982.spv
    0xee90d388713c28fbull, // terrain_761.spv
    0xee946c945eb4db30ull, // terrain_30.spv
    0xeecccee3972dbfa8ull, // terrain_3250.spv
    0xef1954631990b044ull, // terrain_63.spv
    0xef96c7bd9bafea51ull, // terrain_2082.spv
    0xf10e15433692a1bcull, // terrain_819.spv
    0xf14b3a8581bbfe62ull, // terrain_825.spv
    0xf15a8efbd1c47967ull, // terrain_1890.spv
    0xf438e8db8f38ceb4ull, // terrain_96.spv
    0xf4827dc1d1738bb0ull, // terrain_99.spv
    0xf48998a85b9d6079ull, // terrain_2504.spv
    0xf4b2881173489887ull, // terrain_937.spv
    0xf655074b811a086aull, // terrain_1158.spv
    0xf706c1a985d0ae86ull, // terrain_763.spv
    0xf78edcb640bba43aull, // terrain_41.spv
    0xf790ff4fd0af7c87ull, // terrain_416.spv
    0xf7cb6abd00ff0bb0ull, // terrain_2559.spv
    0xf7ec58de96f74e93ull, // planet_0.spv
    0xf9a353239be83db6ull, // terrain_1580.spv
    0xfaea7bc89f049474ull, // terrain_2856.spv
    0xfbef9dd0992e71c8ull, // terrain_1698.spv
    0xfc218303d033a0c9ull, // terrain_2924.spv
    0xfcd37c264ca0fd22ull, // terrain_2607.spv
    0xfd4cd5c626c90433ull, // terrain_2596.spv
    0xfd9a4f1e5ee71f36ull, // terrain_2275.spv
    0xfe0c70b891442cd2ull, // terrain_1634.spv
    0xfe17583c166f55c6ull, // terrain_3078.spv
    0xff07f0ac4e1fc3b8ull, // terrain_2513.spv
};
static const size_t kMvGroundVertCount = sizeof(kMvGroundVert) / sizeof(kMvGroundVert[0]);

static const uint64_t kMvMaskedVert[] = {
    0x016dd883fadc49f2ull, // ocean_meta_data_21.spv
    0x01a38c582946d997ull, // sectional2_0.spv
    0x06bdae11cb928c0full, // light_0.spv
    0x08009728e9ffb917ull, // acf_map_icon_0.spv
    0x0c508f9105d5f18cull, // ocean_meta_data_8.spv
    0x0ec586fe5028972dull, // ground_lights_0.spv
    0x119d2c3fba224273ull, // debug_38.spv
    0x136a830a750139d5ull, // rain_normals_0.spv
    0x1fce95ccd5598b7dull, // ocean_meta_data_12.spv
    0x22700b8df49ebda0ull, // light_vis_2.spv
    0x239ebf5a72948f9aull, // debug_10.spv
    0x27b78e54d19c68fbull, // ocean_readback_2.spv
    0x287b0eb92b365844ull, // particle_4.spv
    0x29765b06f242fe90ull, // profile_view_0.spv
    0x29cf3c39d5598835ull, // light_2.spv
    0x30efc1a62f676685ull, // airport_raster_0.spv
    0x39403cf10a90901full, // cube_filter_raster_0.spv
    0x3f5bddeb2af5c69cull, // scatter_render_atmosphere_5.spv
    0x3f8a558aebcf0d26ull, // ocean_meta_data_0.spv
    0x4357eb082c86af95ull, // line3d_2.spv
    0x57e92b8da6021f85ull, // histo_debug_0.spv
    0x58a2e01018e7bf70ull, // hdr_0.spv
    0x6102668dd9d6054eull, // blit_0.spv
    0x64a300b323510f52ull, // ocean_meta_data_10.spv
    0x66b7f03bf624187bull, // cloud_render_raster_17.spv
    0x68f790ea69c78403ull, // background_blur_0.spv
    0x6bf775e27e5c5427ull, // ocean_meta_data_4.spv
    0x6dbb8a86a7f31340ull, // light_3.spv
    0x6e4aa01dbb4bb91eull, // rain_forces_0.spv
    0x77527b73d6b143a7ull, // light_vis_0.spv
    0x79720cff28a67866ull, // resolve_2.spv
    0x7dd1bd771b470360ull, // scatter_render_atmosphere_0.spv
    0x807a7063203057edull, // debug_39.spv
    0x834a4e8e6ae93eceull, // empty_0.spv
    0x85a8a5144f41f9fdull, // atmosphere_0.spv
    0x91258e9a30ee87adull, // ocean_meta_data_19.spv
    0x9152324436ff25e6ull, // cloud_categorize_0.spv
    0x93852496919a272cull, // cloud_render_raster_0.spv
    0x98fa7972c7f5f6f3ull, // ocean_meta_data_2.spv
    0x992f0450e9cbf3bbull, // svt_0.spv
    0x9969def6fff100b8ull, // empty_2.spv
    0x9be59fddabd9a871ull, // cloud_render_raster_3.spv
    0xa4f8eb4e386d8242ull, // weather_apply_raster_0.spv
    0xa67cefa459b6d0c4ull, // ocean_meta_data_18.spv
    0xa67e87663e965ce0ull, // cloud_map_3.spv
    0xa6c67a91a66bc719ull, // ocean_meta_data_25.spv
    0xa6d626501bcbdd78ull, // particle_3.spv
    0xa97de1ed67bde667ull, // ocean_readback_0.spv
    0xad83f75086640098ull, // depth_resolve_0.spv
    0xb027de32f33676ccull, // volumetric_apply_0.spv
    0xb0fcbb8274e17600ull, // blur_0.spv
    0xbc728ba89221cdb7ull, // wxr_mask_0.spv
    0xc14f34eb412150aaull, // ocean_meta_data_15.spv
    0xc73840f5990aeab4ull, // cloud_map_0.spv
    0xd8652b44a2bb684dull, // msaa_categorize_0.spv
    0xd9d2a21f180c0495ull, // shadow_rect_0.spv
    0xdadbb15ddfcddebcull, // hdr_2.spv
    0xdb5ebd025a66289full, // light_4.spv
    0xdfb37545ceb472d3ull, // line3d_0.spv
    0xe01399271fe13d1aull, // cloud_render_raster_14.spv
    0xe0f6cf5913ffd0efull, // background_blur_2.spv
    0xe11103c30c3935e6ull, // particle_0.spv
    0xee00f2122dfe6f59ull, // ocean_meta_data_9.spv
    0xf62b423b72f14b06ull, // resolve_0.spv
    0xf68ccdf81f29f0ccull, // ocean_meta_data_13.spv
    0xf8a4ba298796fd29ull, // ssr_mesh_0.spv
    0xfa01ccbf65b06c24ull, // blur_2.spv
    0xfafb0aaba0145c34ull, // debug_0.spv
};
static const size_t kMvMaskedVertCount = sizeof(kMvMaskedVert) / sizeof(kMvMaskedVert[0]);

// Sorted array; one binary search per pipeline creation.
static inline bool mvFamilyMasked(uint64_t vertHash)
{
    if (!vertHash) return false;
    const uint64_t *lo = kMvMaskedVert, *hi = lo + kMvMaskedVertCount;
    while (lo < hi) {
        const uint64_t *m = lo + (hi - lo) / 2;
        if (*m == vertHash) return true;
        if (*m < vertHash) lo = m + 1; else hi = m;
    }
    return false;
}

static inline bool mvFamilyGround(uint64_t vertHash)
{
    if (!vertHash) return false;
    const uint64_t *lo = kMvGroundVert, *hi = lo + kMvGroundVertCount;
    while (lo < hi) {
        const uint64_t *m = lo + (hi - lo) / 2;
        if (*m == vertHash) return true;
        if (*m < vertHash) lo = m + 1; else hi = m;
    }
    return false;
}

static inline bool mvFamilyZero(uint64_t vertHash)
{
    if (!vertHash) return false;
    const uint64_t *lo = kMvZeroVert, *hi = lo + kMvZeroVertCount;
    while (lo < hi) {
        const uint64_t *m = lo + (hi - lo) / 2;
        if (*m == vertHash) return true;
        if (*m < vertHash) lo = m + 1; else hi = m;
    }
    return false;
}
