// GENERATED from config/taa_live.ini by tools/gen_live_default.py.
// Do not edit: edit config/taa_live.ini and rebuild.
//
// ---- THE SEED IS THE KNOWN-GOOD CONFIG, WITH ITS KEYS ACTIVE.
//
// writeTemplate() used to emit a documented template with every key COMMENTED
// OUT, so a fresh install fell through to compiled defaults for all of them.
// Chasing those defaults one at a time is how ghosting shipped: taa.mode and
// taa.jitter_scale were found and corrected, and whatever else disagreed was
// not, because nobody had audited the other forty-six.
//
// This file takes precedence over both the environment and the built-in
// default, so seeding it with the tuned config makes a fresh install behave
// identically to the machine it was tuned on BY CONSTRUCTION, rather than by an
// audit that has already been wrong once.
#pragma once

static const char *kLiveDefaultIni =
"# MotionVectors - KNOWN-GOOD LIVE SETTINGS\n"
"#\n"
"# These are tuned values, not defaults. They were established during the\n"
"# shake / crawl / aliasing work and they live ONLY in %TEMP%\\taa_live.ini,\n"
"# which is not part of the repo and is not captured by a folder backup.\n"
"#\n"
"# That cost a whole evening: three builds were restored and compared while\n"
"# this file quietly held probe values from hours earlier, so the comparison\n"
"# measured the settings rather than the builds. Deleting it is worse still -\n"
"# the layer regenerates it EMPTY, so every value silently falls back to a\n"
"# compiled default and the tuning is gone with no message anywhere.\n"
"#\n"
"# So it is version-controlled here, it travels with every backup, and\n"
"# tools/measure/settings.ps1 installs it.\n"
"taa.enable=1\n"
"taa.mode=2\n"
"taa.viz=0\n"
"taa.viz_scale=1.0\n"
"\n"
"# blend\n"
"taa.alpha=0.05\n"
"taa.alpha_moving=0.35\n"
"# px/frame at which alpha_moving is fully applied. Ramped per PIXEL, because\n"
"# cameraMoved is frame-wide and true on a parked, trembling airframe.\n"
"taa.alpha_moving_px=3.0\n"
"taa.gain=4.0\n"
"taa.varclip=8.0\n"
"# Deadband on the clamp correction, in units of the noise floor.\n"
"# 0 = old behaviour, which pinned the blend weight at 1.0 and never accumulated.\n"
"taa.moved_dead=0.0\n"
"taa.novec_alpha=0.05\n"
"taa.reactive=0\n"
"\n"
"# jitter - derived by the layer; unjitter stays OFF because resampling the\n"
"# current frame softens it and the softening accumulates into history\n"
"taa.jitter_scale=1.0\n"
"taa.unjitter=1\n"
"# Catmull-Rom history resampling. Bilinear compounds a blur once per frame\n"
"# for as long as history lives - the motion-only, surface-locked smear.\n"
"taa.hist_catmull=1\n"
"taa.smul_x=0.5\n"
"taa.smul_y=-0.5\n"
"\n"
"# vectors\n"
"taa.vel_scale=1.0\n"
"taa.vel_ypos=0\n"
"taa.vel_max=1.0\n"
"taa.moved_eps=0.0001\n"
"taa.clear_mode=1\n"
"taa.nearfield_m=2.0\n"
"# -1 AUTO (any airframe-mounted view: 1000/1017/1018/1026), 0 never, >1000 pin one.\n"
"# Arming on 1018 alone left the 3-D cockpit (1026) disarmed - the cockpit shake.\n"
"taa.nearfield_view=-1\n"
"taa.mv_pass=-1\n"
"# -1 AUTO (latch only while an ordinal is pinned), 0 never, 1 always.\n"
"# Latching on 1 locked the 5-attachment G-buffer out and blacked the ground.\n"
"taa.sticky_colour=-1\n"
"taa.max_resolves=1\n"
"taa.quad_needs_depth=1\n"
"# 1 = a zero-attribute pipeline must ALSO read a storage buffer to be patched.\n"
"# Depth alone rescued the post-process quads, which stamp the whole frame.\n"
"taa.quad_needs_pull=1\n"
"taa.scene_needs_depth=1\n"
"\n"
"# probes - ALL OFF. Each of these has cost real time by being left set.\n"
"taa.no_motion=0\n"
"taa.no_accum=0\n"
"taa.freeze_history=0\n"
"taa.force_reset=0\n"
"taa.novec_by_vel=0\n"
"taa.novec_cov=-1.0\n"
"taa.coverage=0\n"
"report=0\n"
"report.every=120\n"
"\n"
"# Recycle pool cap while the zone is RED or CRITICAL, in MB. 0 = do not\n"
"# retain device-local blocks under pressure at all (the old behaviour).\n"
"vram.recycle_pressure_mb=64\n"
"crash.enable=0\n"
"crash.discover=0\n"
"crash.occupancy=0\n"
"crash.test_offset=0\n"
"crash.gate=0\n"
"crash.offset_x=0\n"
"crash.offset_y=0\n"
"crash.offset_z=0\n"
"\n"
;
